### ISSUE TITLE
Learn NPM

### ISSUE THREAD

**Issue by atltt** [utk-cs/team-minsky#16]
https://docs.npmjs.com/

We got some more learning to do!

**Comment by robobenklein** [comment]
Note that we will also need to focus on APM: https://github.com/atom/apm

# apm - Atom Package Manager

[![Linux Build Status](https://travis-ci.org/atom/apm.svg?branch=master)](https://travis-ci.org/atom/apm)
[![Windows Build Status](https://ci.appveyor.com/api/projects/status/j6ixw374a397ugkb/branch/master?svg=true)](https://ci.appveyor.com/project/Atom/apm/branch/master)
[![Dependency Status](https://david-dm.org/atom/apm.svg)](https://david-dm.org/atom/apm)

Discover and install Atom packages powered by [atom.io](https://atom.io)

You can configure apm by using the `apm config` command line option (recommended) or by manually editing the `~/.atom/.apmrc` file as per the [npm config](https://docs.npmjs.com/misc/config).

## Relation to npm

apm bundles [npm](https://github.com/npm/npm) with it and spawns `npm` processes to install Atom packages. The major difference is that `apm` sets multiple command line arguments to `npm` to ensure that native modules are built against Chromium's v8 headers instead of node's v8 headers.

The other major difference is that Atom packages are installed to `~/.atom/packages` instead of a local `node_modules` folder and Atom packages are published to and installed from GitHub repositories instead of [npmjs.com](https://www.npmjs.com/)

Therefore you can think of `apm` as a simple `npm` wrapper that builds on top of the many strengths of `npm` but is customized and optimized to be used for Atom packages.

**Comment by robobenklein** [comment]
@atltt @RexRascerX 

Once you guys get the plugin to install and load into Atom in development mode, please check off your box so I can close this:

 - [ ] @atltt 
 - [ ] @RexRascerX 
 - [ ] @ilumsden

**Comment by RexRascerX** [comment]
I set dev to true. That is what we needed to do, right?

**Comment by atltt** [comment]
We know enough!
